
AA_counts={
"A":4,
"R":6,
"D":2,
"N":2,
"C":2,
"E":2,
"Q":2,
"G":4,
"H":2,
"I":3,
"L":6,
"K":2,
"M":1,
"F":2,
"P":4,
"S":6,
"T":4,
"W":1,
"Y":2,
"V":4
}

s1="MRFYGSYLHWWVKLMSSSACSCLHFIHHMSTWRYWLDHGYYTRCMQFRWQTQCWCTHKCRYYAKFDLWSFNSIWNHSGHETACNSMTWMPTDYTLEQAGAKWGCLNNNDPPGTRYWVDKPTPWYKDTAITHSNVMDHMVVEEKHNDMHIWWVAWWWHPPQTHMDWMCEDVMNLCEYYPGYYHNMPNRYYNELGGVQPVYVPMYNSMDDHWWFMIEAWLVGISNHQSGRLACIQQKDERVYKHMVWTQDYDHVHMVWFRVSGAETCKTEHWCMENAEDGIKMKKHCVQNMLGWPWPERSSCMAVAHIEMKRPSRTHFVEVWNAYMHFNVMENKIYSTKWPAVNDGKSVAMFDQVFRMEWHDDDVFFCHLCALSDVVAMKLPLVQYWNHKKLNYDHWFTWLMDRAHPVVMIYCHIMETMKRCVRVSTGPACGKHLPQSQCCDDENTFLDSRQGGFQAEDRISHEAGPCENGHEIPHHVIQYMFSVRIVWATGDMLQSPNSCMCMLYPCYGIVLDNRWKHCPEVQAYHGRAFTWTTDKMANQRWHSIWSPDGSAPSYYSKSEQANSEAWDGYDLNTIQLAHDIDCMAQNSWHMYTTFCQIYITCEDMPCFYHRMTRTFVMNSYRTIILLAEVIHVISGRGHPEMFPNIVVTNCFAEGRNKKQNLWLCDMYQENTEASFVLYYGWYKQADIEKCRKNFYAMQLMCYTVWVVRDHSWSRLRKVSENAHHGLTDFVYCFSKALEDSEDFLTYANDFDCLPCLLGTNENYYCMLFDNFIYRDARAQAPGAPQGAYMLCSTGPQDVDWDFYNQWQCNLEYNTHPWTNAEELEQTCRGSRRCFSAQMYYAMRYNWLQIRYGNCDCLVMDFYYYDEWLYMIEHYRPQIDIYLWDHCRHPYTMWHVTLWRLNSMGEHHMGCLPPDLKLGRPNHWKMAKVKTQNLTVKVMCNGSRTTLWVQWQTVWPYFWPKTQRFPKCGAWADRYCRWPLKCVHYIKHIHNVDEKVSKYKI"
mod=1
for i in range(0,len(s1)):
	mod=mod*AA_counts[s1[i]]
	if(mod>1000000):
		mod=mod%1000000
		
mod=(mod*3)%1000000

print(mod)
	
